### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by EmmaSweeney** [kingrpaul/p-t-barnum_the-humbugs-of-the-world#1]
- [x]  Please run `se typogrify .` again.

- [x] Please run `se semanticate .` again.

local.css:
- [x]  You are missing CSS for full-page epigraphs. See [Section 7.4.4.3](https://standardebooks.org/manual/1.5.0/7-high-level-structural-patterns#7.4.4.3) in the manual.

- [x] You are missing CSS for letters. See [Section 7.7](https://standardebooks.org/manual/1.5.0/7-high-level-structural-patterns#7.7) in the manual.

- [x] You are missing some CSS for verse. See [Section 7.5](https://standardebooks.org/manual/1.5.0/7-high-level-structural-patterns#7.5) in the manual.

Epigraph:
- [x] I recommend placing the first line outside of the blockquote. It isn't quoted text.

- [x] In the page scans, the first line is in capital letters. You can surround it with a `<b>` and it will automatically turn it small caps. If you want to make it capital letters, then go ahead and add CSS that targets the `<b>`.

- The first line in the epigraph is also divided into 3 lines. If you want to, you can use `<br/>`s to mimic this. But this is really nitpicky stuff.

- [x] Typically we try to avoid using different fonts, especially if the page scans don't call for it. I recommend just following the manual's styling, and the lint error will go away.

Publisher’s Note:
- [x] Convert the chapter semantics to preface.

Introduction:
- [x] Convert the chapter semantics to introduction.

Titles:
- [x] The titles for both your parts and chapters need to match the manual. See[ section 7.2.9](https://standardebooks.org/manual/1.5.0/7-high-level-structural-patterns#7.2.9) in the manual.

- [x] Make sure to delete the periods after the roman numerals in the parts.

- [x] Please run `se print-title --in-place src/epub/text/*` This will correct your `<title>` elements. Bridgeheads should not appear in these elements.

Bridgeheads:
- [x] Your bridgeheads are title cased. Please convert these to sentence case. See the last example in [Section 7.2.11](https://standardebooks.org/manual/1.5.0/7-high-level-structural-patterns#7.2.11) in the manual.

Abbreviated US States:
- [x] "Postal codes and abbreviated US states are set in all caps, without periods or spaces, and are wrapped in an `<abbr class="postal">` element." [Section 8.10.6](https://standardebooks.org/manual/1.5.0/8-typography#8.10.6) in the manual.

chapter-2-17.xhtml:
- [x] (`<abbr>Dr.</abbr> <abbr class="name">V.</abbr> <abbr class="name">V.</abbr>`) --> (`<abbr>Dr.</abbr> <abbr class="name">V. V.</abbr>`)

chapter-3-21.xhtml:
- [x]  You are missing some `<abbr>`s and `<abbr class="name">`s, mostly in the second paragraph.

chapter-4-25.xhtml:
- [x] Itemized tables like this need to put the total amount in a `<tfoot>`.
```
`								</td>
							</tr>
						</tbody>
						<tfoot>
							<tr>
								<td>Total exactly</td>
								<td>$1,000.00</td>
							</tr>
						</tfoot>
					</table>`
```

- [x] To add a line in between the list and total, add this CSS:
```
table tfoot td:last-child{
  border-top: 1px solid;
}
```
chapter-7-38.xhtml:
- The crosses are very interesting; I don't believe we have encountered this before! I will ask about this in the chat.

- [x] `i.e.`s and other Latinisms like these should not be italicized. [Section 8.9](https://standardebooks.org/manual/1.5.0/8-typography#8.9) in the manual.

- [x] Instead of applying xml:lang tags to each verse line, add a single language tag to the surrounding `<blockquote>`.

chapter-8-41.xhtml:
- [x] There are some "v"s that are marked as roman numerals. These should be lower cased, italicized, and tagged as graphemes. [Section 8.2.8.1](https://standardebooks.org/manual/1.5.0/8-typography#8.2.8.1) in the manual.

Long Description:
- [x] "As raconteur" --> "As a raconteur"

- [x] "state level" --> "state-level"

- [x] "razzle dazzle" --> "razzle-dazzle"

- [x] "a little more wise" --> "wiser"

- [x] You need a comma before "and the razzle-dazzle of modern"

- [x] Remove the comma before "and opening an intimate window"

content.opf:

- [x] The nacoaf link for Charles Caleb Ward is not right. If you can't find a link when you search the Library of Congress Names Database then just delete that section.

ToC:
- [x] Since your `<title>` elements have changed you will need to rebuild your ToC.

**Comment by kingrpaul** [comment]
@EmmaSweeney: Converted crosses in chapter-7-38.xhtml to svg -- look good?

**Comment by kingrpaul** [comment]
thanks
