### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by EmmaSweeney** [kingrpaul/p-t-barnum_the-humbugs-of-the-world#2]
Titles:

- [x] All Parts titles need to look like this:
```
			<hgroup>
				<h2 epub:type="ordinal z3998:roman">I</h2>
				<h3 epub:type="title">Personal Reminiscences</h3>
			</hgroup>

```
- [x]  All Chapter titles need to look like this:
```
					<h3>
						<span epub:type="label">Chapter</span>
						<span epub:type="ordinal z3998:roman">I</span>
					</h3>
```
- [x] Run `se print-title --in-place src/epub/text/*` after you have made the above changes.

local.css:
- [x] Add this styling for the epigraph:
```
[epub|type~="epigraph"] i{
	font-style: normal;
}
```

Images:
- [x] You need a List of Illustrations. See [Section 7.9](https://standardebooks.org/manual/1.5.0/7-high-level-structural-patterns#7.9) in the manual.

- [x] Instead of using one image for all crosses, use an image of a single cross and an image of 3 three crosses. This will make it easier to link to the LoI.

- [x] Please add the source images you used for making the SVGs to the images file that also contains the cover.source.jpg. This is if a problem occurs with the SVGs in the future.

- [x] "That attribute's name is illustration- followed by -N, where N is the sequence number of the element starting at 1." [Section 7.8.1.1](https://standardebooks.org/manual/1.5.0/7-high-level-structural-patterns#7.8.1.1) in the manual.

- [x] "The alt attribute is one or more complete sentences ended with periods or other appropriate punctuation. It is not composed of sentence fragments or complete sentences without ending punctuation." [Section 7.8.2.2](https://standardebooks.org/manual/1.5.0/7-high-level-structural-patterns#7.8.2.2) in the manual.

content.opf:
- [x] If you don't know who wrote the publisher's notes, you can give the author the MARC relator "wpr."

- [x] Makes sure to rebuild the manifest and spine after creating the loi.xhtml

chapter-1-1.xhtml:
- [x] In the bridgehead, capitalize the "in" (⁠—​in politics⁠—).

chapter-7-38.xhtml:
- [x] The `epub:type="inscription"` is not a real attribute. I recommend surrounding the inscription with a `<blockquote>`. Then, you can target the first blockquote in the file like this:
```
#chapter-7-38 blockquote:first-of-type{
	text-align: center;
	text-indent: 0;
}
```
- [x] There is a typo in the bridgehead (⁠—​The secret name ff God⁠—​).

ToC:
- [x] Since your `<title>` elements have changed you will need to rebuild your ToC.

se-lint-ignore.xml
- After all the changes, you should only ignore the s-054 lint error.

**Comment by kingrpaul** [comment]
From the style-guide: "If an ebook has any illustrations that are **major structural components** of the work (even just one!), then the ebook includes an loi.xhtml file at the end of the ebook."  The words "major structural components" would seem intended to exclude a thing like this symbol and a triple-cross  would not be "DRY" and would only be an improvement in simplifying an LOI.

**Comment by EmmaSweeney** [comment]
There are other productions that include symbols and link them to an LoI. The crosses are important for the understanding of that particular chapter.

**Comment by kingrpaul** [comment]
> There are other productions that include symbols and link them to an LoI. The crosses are important for the understanding of that particular chapter.

Do you have an existing title I can refer to?

**Comment by EmmaSweeney** [comment]
My Divine Comedy production contains a geomantic symbol. If I recall correctly, M. R. James' Short Fiction had swastikas.

**Comment by kingrpaul** [comment]
> My Divine Comedy production contains a geomantic symbol. If I recall correctly, M. R. James' Short Fiction had swastikas.

The LOI required that I put a `<figure>` around the image. I'm paralleling the layout of James, as best I can tell and it lints ok. Yet, when I try to build the ebook, I get `(47,585): Error while parsing file: element "figure" not allowed here; expected ...`. Do you see something here I am missing? Thanks in advance.

**Comment by EmmaSweeney** [comment]
Hmm... There seems to be a conflict between the manual's instructions and lint. I recommend removing the `<figure>`s, moving the ids to the `<img>` elements, and adding this error to the se-lint-ignore.xml. This will follow the manual and appease epubcheck. I think this is another weird requirement from the new epubcheck version. Since we don't include images very often, requirements are usually updated last.

By the way, instead of using `class="sigil"` to target the images, target with "`#chapter-7-38 img`" instead. Make sure to remove the class. We don't like using unique classes for only two things.

**Comment by EmmaSweeney** [comment]
Alex says delete the ids and LoI.

**Comment by kingrpaul** [comment]
The table of prices still justifies left on the android kindle app, though it looks right in a browser.

**Comment by EmmaSweeney** [comment]
> The table of prices still justifies left on the android kindle app, though it looks right in a browser.

I opened the azw3 file with Calibre. Everything seems to be in order. People have said in the google chat that there is a specific way to upload SE books to Kindle ereaders.
